apiVersion: v1
kind: Service
metadata:
  name: reusable-workflows-tester
  labels:
    app: reusable-workflows-tester
spec:
  type: ClusterIP
  selector:
    app: reusable-workflows-tester
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http
      name: http

